### ISSUE TITLE
Rails.catch.fetch doesn't properly serialize ContentfulModels

### ISSUE THREAD

**Issue by zrisher** [contentful/contentful_rails#10]
Let's say we have a `ContentfulModel` named `Company` with several fields and associations. If we do:

```
  def company
    Rails.cache.fetch("some_cache_key") do
      Company.first
    end
  end
```

The first time we call `company` we'll receive the a `Company`. The second time, we'll receive an `Array` with some of its associations (but none of its field values). The second time we're loading the result from the cache, so this leads me to believe the ContentfulModel is not being marshalled correctly.

If instead we do:

```
  def company
    marshalled = Rails.cache.fetch("some_other_cache_key") do
      Marshal.dump(Company.first)
    end

    Marshal.load(marshalled)
  end
```

We get the `Company` back every time, which I believe confirms my suspicion that this is a marshalling problem with `ContentfulModel`. 

I'm pretty unfamiliar with the inner workings of `Rails.cache`, but it seems like this is hopefully an easy problem to solve. Likely `ContentfulModel` is not quite behaving as Rails expects it to.

**Comment by zrisher** [comment]
This comment from #11 is instructive:

> The correct solution is to be able to derive a Contentful model completely from the cache but unfortunately it's harder than it seems to generate one from a webhook in the first place, because the Contentful library (used by ContentfulModel and ContentfulRails) can't instantiate an entry (or asset or whatever) from JSON - only from a call to the API.

> Basically this is an unsolved problem.

> My suggested / planned solution is probably to subclass ContentfulModel::Base and include some way of marshalling the whole thing into the cache. Then you could hook into the instrumentation call raised when a web hook arrives, hit the api, and update it. At the moment there is a recursion issue in the underlying Contentful library which needs working around before the marshalling will work.

**Comment by pxlpnk** [comment]
@edtjones & @zrisher there is a way that would allow to create an entry without a making an api call: 
https://gist.github.com/neonichu/17a987aeeb256d4bf6f3

this is a bit hackish. I think it would make sense to open a ticket at 
https://github.com/contentful/contentful.rb 
and discuss this there. It would be a huge benefit to improve caching if this was possible.

**Comment by dlitvakb** [comment]
This has been solved for over a year. Closing.

**Comment by swetonic** [comment]
I encountered a problem recently that required me to do the Marshal.dump/Marshal.load trick. I have a content model that includes references to other pieces of content. The first time my content is put in the rails cache, it's fine. But the second time, when reading the cached entry, one of the properties is returned as a Contentful::Link instead of a Contentful::Asset. 

If I do Marshal dump/load the content is a Contentful::Link always. I can then resolve the link, but of course I'd love to avoid that resolve call.

**Comment by dlitvakb** [comment]
Hey @swetonic,

I have identified this issue and I'm currently working on fixing it, it happens when doing `Marshal.load` on objects which previously had unpublished nested resources.

The inclusion errors were not serlialized, therefore the links were being displayed instead of removed from the result.

I'll be publishing a fix today on the https://github.com/contentful/contentful.rb gem.

Cheers
